### ISSUE TITLE
Workshop Patch

### ISSUE THREAD

**Issue by FatherSarge** [FWolfe/ProfessionsFramework#5]
Hey all, this other workshop mod apparently fixes a bug that your original still has, not sure why it hasn't been brought up as an issue here before. I'm not the patch author just hopefully bringing it to your attention. Mods are using one of the other, causing issues.

https://steamcommunity.com/workshop/filedetails/?id=2216760107

**Comment by FWolfe** [comment]
Eh the "bug" that workshop upload attempted to fix (removal of hypochondriac) was fixed in this version [Oct 2019](https://github.com/FWolfe/ProfessionFramework/commit/7b9d2c979e37528debb4ea37a741046624f368d9).

That workshop upload is drastically out of date, and tbh horribly done as a "patch" since the person uploaded a edited full copy of the mod, instead of a single file with a single line in it (and making the other workshop upload a requirement):
```lua
ProfessionFramework.Traits["Hypercondriac2"] = nil
```

Because they decided to upload a edited version instead of just the above line is whats causing the incompatibility issues between the 2 workshop versions.
